---
- name: Nginx Configure | Modules | Make sure the naxsi_module configuration is up to date when enabled
  template:
    src: modules/naxsi_core.rules
    dest: "{{nginx_dir}}/naxsi_core.rules"
    owner: root
    group: root
    mode: 0644
  when: nginx_naxsi_module is defined and nginx_naxsi_module == true

- name: Nginx Configure | Modules | Make sure the naxsi_module configuration is removed when disabled 
  file:
    path: "{{nginx_dir}}/naxsi_core.rules"
    state: absent
  when: nginx_naxsi_module is not defined or nginx_naxsi_module == false

- name: Nginx Configure | Modules | Make sure we have a basic set of rules to include for our sites configs
  template:
    src: modules/naxsi.rules
    dest: "{{nginx_dir}}/naxsi.rules"
    owner: root
    group: root
    mode: 0644
  when: nginx_naxsi_module is defined and nginx_naxsi_module == true

